services:
  reverse-proxy:
    image: jc21/nginx-proxy-manager
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - nginx-proxy-manager_data:/data
      - nginx-proxy-manager_letsencrypt:/etc/letsencrypt

networks:
  frontend:
    external: true

volumes:
  nginx-proxy-manager_data:
  nginx-proxy-manager_letsencrypt:
