version: "3"
services:
  app:
    image: portainer/portainer-ce:latest
    networks:
      - frontend
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  frontend:
    external: true

volumes:
  data:
